const serviciosFisioterapia = [
    {
        id: 1,
        image: "masaje-relajante.jpg",
        title: "Masaje Relajante",
        description: "Un masaje suave que ayuda a relajar los músculos y mejorar la circulación.",
        duration: 60,
        objetive: "Reducir el estrés y la tensión muscular",
        technique: "Masaje sueco",
        benefits: ["Alivio del estrés", "Mejora la circulación", "Relajación muscular"],
        price: 50,
        category: "Masajes"
    },
    {
        id: 2,
        image: "masaje-descontracturante.jpg",
        title: "Masaje Descontracturante",
        description: "Masaje intensivo para tratar áreas con contracturas y nudos musculares.",
        duration: 60,
        objetive: "Aliviar contracturas musculares",
        technique: "Masaje profundo",
        benefits: ["Alivio del dolor", "Reducción de contracturas", "Mejora la movilidad"],
        price: 70,
        category: "Masajes"
    },
    {
        id: 3,
        image: "rehabilitacion-rodilla.jpg",
        title: "Rehabilitación de Rodilla",
        description: "Programa de ejercicios y terapias para recuperar la funcionalidad de la rodilla después de una lesión.",
        duration: 90,
        objetive: "Recuperar la movilidad y fuerza en la rodilla",
        technique: "Terapia manual y ejercicios terapéuticos",
        benefits: ["Recuperación de la movilidad", "Fortalecimiento muscular", "Reducción del dolor"],
        price: 80,
        category: "Rehabilitación"
    },
    {
        id: 4,
        image: "estiramientos.jpg",
        title: "Estiramientos Guiados",
        description: "Sesiones de estiramientos guiados por un fisioterapeuta para mejorar la flexibilidad y prevenir lesiones.",
        duration: 45,
        objetive: "Mejorar la flexibilidad y prevenir lesiones",
        technique: "Estiramientos asistidos",
        benefits: ["Aumento de la flexibilidad", "Prevención de lesiones", "Mejora la postura"],
        price: 40,
        category: "Ejercicios Terapéuticos"
    },
    {
        id: 5,
        image: "drenaje-linfatico.jpg",
        title: "Drenaje Linfático",
        description: "Técnica de masaje suave que estimula el sistema linfático para reducir la retención de líquidos.",
        duration: 60,
        objetive: "Reducir la retención de líquidos",
        technique: "Drenaje linfático manual",
        benefits: ["Reducción de la hinchazón", "Mejora la circulación linfática", "Desintoxicación"],
        price: 60,
        category: "Masajes"
    },
    {
        id: 6,
        image: "terapia-craneosacral.jpg",
        title: "Terapia Craneosacral",
        description: "Terapia suave que trabaja sobre el sistema craneosacral para aliviar tensiones y mejorar el bienestar.",
        duration: 60,
        objetive: "Equilibrar el sistema craneosacral",
        technique: "Terapia craneosacral",
        benefits: ["Alivio del dolor de cabeza", "Reducción del estrés", "Mejora el equilibrio corporal"],
        price: 75,
        category: "Terapias Especializadas"
    },
    {
        id: 7,
        image: "electroterapia.jpg",
        title: "Electroterapia",
        description: "Uso de corrientes eléctricas para aliviar el dolor y estimular la contracción muscular.",
        duration: 30,
        objetive: "Aliviar el dolor y estimular los músculos",
        technique: "Estimulación eléctrica",
        benefits: ["Alivio del dolor", "Estimulación muscular", "Mejora la circulación"],
        price: 55,
        category: "Terapias Instrumentales"
    },
    {
        id: 8,
        image: "punción-seca.jpg",
        title: "Punción Seca",
        description: "Técnica que utiliza agujas para tratar puntos gatillo y aliviar el dolor muscular.",
        duration: 45,
        objetive: "Tratar puntos gatillo musculares",
        technique: "Punción seca",
        benefits: ["Alivio del dolor muscular", "Reducción de puntos gatillo", "Mejora la movilidad"],
        price: 65,
        category: "Terapias Especializadas"
    },
    {
        id: 9,
        image: "rehabilitacion-espalda.jpg",
        title: "Rehabilitación de Espalda",
        description: "Programa de rehabilitación para tratar dolores y lesiones en la espalda, incluyendo la columna vertebral.",
        duration: 90,
        objetive: "Tratar dolores y lesiones de espalda",
        technique: "Terapia manual y ejercicios específicos",
        benefits: ["Alivio del dolor de espalda", "Mejora la postura", "Fortalecimiento muscular"],
        price: 85,
        category: "Rehabilitación"
    },
    {
        id: 10,
        image: "masaje-deportivo.jpg",
        title: "Masaje Deportivo",
        description: "Masaje diseñado para deportistas, enfocado en prevenir y tratar lesiones relacionadas con la actividad física.",
        duration: 60,
        objetive: "Prevenir y tratar lesiones deportivas",
        technique: "Masaje deportivo",
        benefits: ["Prevención de lesiones", "Mejora el rendimiento", "Recuperación muscular"],
        price: 70,
        category: "Masajes"
    },
    {
        id: 11,
        image: "terapia-ocupacional.jpg",
        title: "Terapia Ocupacional",
        description: "Terapia enfocada en mejorar la capacidad para realizar actividades cotidianas después de una lesión o enfermedad.",
        duration: 60,
        objetive: "Mejorar la funcionalidad en actividades diarias",
        technique: "Ejercicios funcionales",
        benefits: ["Mejora la independencia", "Recuperación funcional", "Aumento de la confianza"],
        price: 90,
        category: "Terapias Especializadas"
    },
    {
        id: 12,
        image: "rehabilitacion-postoperatoria.jpg",
        title: "Rehabilitación Postoperatoria",
        description: "Programa de rehabilitación diseñado para recuperar la movilidad y funcionalidad después de una cirugía.",
        duration: 90,
        objetive: "Recuperar la movilidad después de una cirugía",
        technique: "Terapia manual y ejercicios terapéuticos",
        benefits: ["Recuperación de la movilidad", "Reducción del dolor", "Prevención de complicaciones"],
        price: 100,
        category: "Rehabilitación"
    },
    {
        id: 13,
        image: "masaje-prenatal.jpg",
        title: "Masaje Prenatal",
        description: "Masaje suave y seguro diseñado para aliviar las molestias comunes durante el embarazo.",
        duration: 60,
        objetive: "Aliviar molestias durante el embarazo",
        technique: "Masaje prenatal",
        benefits: ["Alivio del dolor lumbar", "Reducción de la hinchazón", "Relajación"],
        price: 60,
        category: "Masajes"
    },
    {
        id: 14,
        image: "terapia-frio-calor.jpg",
        title: "Terapia de Frío y Calor",
        description: "Uso alternado de frío y calor para reducir la inflamación y aliviar el dolor muscular.",
        duration: 30,
        objetive: "Reducir la inflamación y el dolor",
        technique: "Crioterapia y termoterapia",
        benefits: ["Reducción de la inflamación", "Alivio del dolor", "Mejora la circulación"],
        price: 45,
        category: "Terapias Instrumentales"
    },
    {
        id: 15,
        image: "rehabilitacion-cervical.jpg",
        title: "Rehabilitación Cervical",
        description: "Programa de rehabilitación para tratar dolores y lesiones en la zona cervical y mejorar la movilidad.",
        duration: 60,
        objetive: "Tratar dolores y lesiones en la zona cervical",
        technique: "Terapia manual y ejercicios específicos",
        benefits: ["Alivio del dolor cervical", "Mejora la movilidad", "Reducción de la tensión"],
        price: 75,
        category: "Rehabilitación"
    }
];

export default serviciosFisioterapia;